### ISSUE TITLE
Stackdriver V2 API

### ISSUE THREAD

**Issue by snowp** [GoogleCloudPlatform/cloud-trace-java#100]
What's the plan for adding support for the V2 API? I'm not sure if the Stackdriver UI even supports the new features (like linked spans) right now, but I'm curious to know if there's any concrete plans to add support for this in the SDK.

**Comment by bogdandrutu** [comment]
We are focusing on switching users of this library to opencensus for instrumentation:
* http://opencensus.io
* https://github.com/census-instrumentation/opencensus-java

Probably this library will no longer be updated to v2.

**Comment by amohabir** [comment]
Would it be helpful to put this information in the README?

**Comment by snowp** [comment]
Thanks for the clarification. I'll look into moving our internal usage of Stackdriver over to opencensus. I second the idea of adding this information to the README. It would also be nice to have this be reflected in the official Stackdriver documentation, pointing this https://cloud.google.com/trace/docs/client-libraries to opencensus instead. 

Closing this since the original question has been answered.
